version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=dev-secret-key
      - CORS_ORIGINS=http://localhost:8081,http://localhost:19006
      - PORT=8080
    volumes:
      # Mount volumes for persistent storage during development
      - ./backend/uploads:/app/uploads
      - ./backend/audiobooks:/app/audiobooks
      # Mount source code for development (comment out for production)
      - ./backend:/app
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  # Optional: Add Redis for production job queue (commented for MVP)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

# volumes:
#   redis_data: